name: src

on:
  push:
    paths:
      - 'src/**'
      - '**.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Install gcc
        run: |
          wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
          tar -xf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
          echo `pwd`/gcc-arm-none-eabi-10-2020-q4-major/bin >> $GITHUB_PATH

      - name: Build templete
        working-directory: src/templete
        run: |
          mkdir build && cd build
          cmake -D CROSS_COMPILER_PATH=../gcc-arm-none-eabi-10-2020-q4-major ..


      - uses: actions/upload-artifact@v2
        with:
          name: templete
          path: src/templete/build
